[project]
name = "client"
version = "0.1.0"
description = "Simple USB KVM client"
readme = "README.md"
authors = [
    { name = "lay.zhan", email = "lay.zhan@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "hidapi>=0.15.0",
    "loguru>=0.7.3",
    "nuitka>=4.2",
    "pych9329>=0.1.6",
    "pyside6>=6.11.2",
    "pywinhook",
    "pyyaml>=6.0.3",
]

[project.scripts]
client = "client:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
